
services:
  chavo-postgres:
    image: postgres:16-alpine
    container_name: chavo-env-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  chavo-postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations
    depends_on:
      chavo-postgres:
        condition: service_healthy

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: chavo-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:chavo-postgres:5432
    ports:
      - "127.0.0.1:5432:5432"
    depends_on:
      - chavo-postgres

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: chavo-auth
    environment:
      - AUTH_DB_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@chavo-postgres:5432/${AUTH_DB_NAME}?sslmode=disable
      - ENV=${ENV}
      - AUTH_PORT=${AUTH_PORT}
    depends_on:
      chavo-postgres:
        condition: service_healthy